wydy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from user.forms import LoginForm
from django.contrib.auth import views as auth_views
admin.autodiscover()

urlpatterns = patterns('')

urlpatterns += patterns('',
    url(r'^admin/', include(admin.site.urls)),
)

urlpatterns += patterns('home.views',
    url(r'^$', 'home', name='home'),
    url(r'^about/$', 'about', name='about'),

    url(r'^thanks/$', 'thanks', name='thanks'),
    url(r'^major_id/$', 'major_id', name='major_id'),
)

urlpatterns += patterns('user.views',
    url(r'^join/$', 'join',name='join'),
    #url(r'^browser_support/$','browser_support',name='browser_support'),

    url(r'^contact/$', 'contact',name='contact'),

    url(r'^login/$', auth_views.login, {'template_name': 'login.html', 'authentication_form': LoginForm }, name = 'login'),

    url(r'^reset/$', 'reset_psw',name='reset_psw'),
    url(r'^reset/confirm/(?P<uid>\w+)/(?P<token>[-\w]+)/$', 'reset_psw_confirm', name = 'reset_psw_confirm'),
    #   url(r'^user/(?P<user_id>\d+)/$','user',name='user'),

    url(r'^user/tasklist/$', 'tasklist',name='tasklist'),

    #url(r'^hot/$','hot',name='hot'),
    url(r'^logout/$', auth_views.logout, {'template_name': 'user.html','next_page':'/login/'}, name='logout'),
    url(r'^settings/(?P<item>\w+)/$', 'settings', name='settings'),

    (r'user/create/$', 'create_user'),
    (r'user/list/$', 'list_user' ),
    (r'user/edit/(?P<id>[^/]+)/$', 'edit_user'),
    (r'user/view/(?P<id>[^/]+)/$', 'view_user'),
)

urlpatterns += patterns('fileupload.views',
    url(r'^file/uploadhandle/(?P<user_id>\d+)/(?P<ord_id>\d+)/(?P<req_id>\d+)/$', 'upload_handle',name='upload-handle'),
    url(r'^file/upload/(?P<user_id>\d+)/(?P<ord_id>\d+)/(?P<req_id>\d+)/$', 'upload',name='upload-new'),

    url(r'^file/success/(?P<ord_id>\d+)/$', 'success',name='success'),

    url(r'^file/$', 'order',name='order'),
    url(r'^file/add/(?P<user_id>\d+)/(?P<ord_id>\d+)/$', 'add',name='add'),
    url(r'^file/cancel/(?P<user_id>\d+)/(?P<ord_id>\d+)/$', 'cancel',name='cancel'),

    url(r'^file/requirement/(?P<user_id>\d+)/(?P<ord_id>\d+)/$', 'requirement',name='requirement'),
)

urlpatterns += patterns('download.views',
    url(r'^download/(?P<ord_slug>\S+)/$', 'download_zipfile',name='download_zipfile'),
    url(r'^download/filelist/(?P<s>\w+)$', 'download_filelist',name='download_filelist'),
)

urlpatterns += staticfiles_urlpatterns()

home/models.py
from django.db import models

# Create your models here.

user/forms.py
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm, SetPasswordForm, PasswordChangeForm
from django.contrib.auth.models import User
from django.forms.util import ErrorList
from django.forms import ModelForm
from models import Card

class LoginForm(AuthenticationForm):
    username = forms.CharField(error_messages = {'required': u'用户名不能为空诶童鞋～'},max_length = 10,min_length=8)
    password = forms.CharField(error_messages = {'required': u'密码不能为空诶少年～'},max_length = 16,min_length = 8,widget = forms.PasswordInput)
    def clean(self):
            username = self.cleaned_data.get('username')
            password = self.cleaned_data.get('password')
            if username and password:
                self.user_cache = authenticate(username=username, password=password)
                if self.user_cache is None:
                        raise forms.ValidationError("密码错误啦~")
            self.check_for_test_cookie()
            return self.cleaned_data




class JoinForm(forms.Form):
	cardNumber = forms.IntegerField(error_messages = {'required': u'请填写卡号',})
	cardPassword = forms.CharField(error_messages = {'required': u'请填写卡密'})
	username = forms.CharField(error_messages = {'required': u'请填写用户名','max_length':u'研究生是10位哦','min_length':u'本科生8位哦'},min_length=8, max_length = 10)
	password = forms.CharField(error_messages = {'required': u'密码不能为空哦','max_length':u'至少8位啦','min_length':u'最多16位呢'},widget = forms.PasswordInput,max_length = 16,min_length=8)
	confirm_password = forms.CharField(error_messages = {'required': u'确认密码不能为空哦','max_length':u'至少8位啦','min_length':u'最多16位呢'},widget = forms.PasswordInput,max_length=16,min_length=8)
	email = forms.EmailField(error_messages = {'required': u'请填写邮箱'})
	phone = forms.CharField(error_messages = {'required': u'怎么能不写呢','max_length':u'给记错自己手机号码的人跪了..','min_length':u'给记错自己手机号码的人跪了..'},widget = forms.TextInput(),max_length = 11,min_length=11)
    
        def clean_cardNumber(self):
            cardNumber = self.cleaned_data['cardNumber']
            exists = Card.objects.filter(number = cardNumber).count() > 0
            if not exists:
                raise forms.ValidationError(u'卡号不存在或已被使用了哦，请重新输入或购买~')
            return cardNumber
        def clean_cardPassword(self):
            cardPassword = self.cleaned_data['cardPassword']
            exists = Card.objects.filter(password=cardPassword).count() > 0
            if not exists:
                raise forms.ValidationError(u'卡密输入错误~')
            return cardPassword
        def clean_phone(self):
            phone = self.cleaned_data['phone']
            if phone[0]!='1':
                raise forms.ValidationError(u'难道墙内的手机不是1开头么少年..')
            if not phone.isdigit():
                raise forms.ValidationError(u'请用阿拉伯数字哦亲~')
        
    
        def clean_username(self):
            username = self.cleaned_data['username']
            exists = User.objects.filter(username = username).count() > 0
            if exists:
                raise forms.ValidationError(u'该用户名已被使用了呢，请重新输入')
            if not username.isdigit():
                raise forms.ValidationError(u'学号是数字哦')
            return username
    
        def clean(self):
            if ('confirm_password' in self.cleaned_data) and ('password' in self.cleaned_data):
                if (self.cleaned_data['confirm_password'] != self.cleaned_data['password']):
                    self._errors["confirm_password"] = ErrorList([u'密码与确认密码不匹配耶～'])
                    del self.cleaned_data['password']
                    del self.cleaned_data['confirm_password']
            if ('cardPassword' in self.cleaned_data)and ('cardNumber' in self.cleaned_data):
                cardPassword = self.cleaned_data['cardPassword']
                cardNumber = self.cleaned_data['cardNumber']
                card = Card.objects.get(number=cardNumber)
                if card.password != cardPassword:
                    self._errors["cardPassword"] = ErrorList([u'卡密与卡号不对应呢，请重新输入或购买~'])
                    del self.cleaned_data['cardNumber']
                    del self.cleaned_data['cardPassword']
                
            return self.cleaned_data
    
        def clean_email(self):
            email = self.cleaned_data['email']
            exists = User.objects.filter(email = email).count() > 0
            if exists:
                raise forms.ValidationError(u'邮箱已经被使用了呢，请更换邮箱')
            return email



class GetPasswordForm(forms.Form):
    email = forms.EmailField(max_length = 75, widget = forms.TextInput())
    def clean_email(self):
        email = self.cleaned_data['email']
        if User.objects.filter(email = email).count() != 1:
            raise forms.ValidationError("这个邮箱木有对应的帐号诶～")
        return email

class ChangePasswordForm(PasswordChangeForm):
    old_password  = forms.CharField(label="原密码", widget=forms.PasswordInput, error_messages = {'required': u'新密码不能为空哦', 'min_length':u'至少8个字符啦', 'max_length':u'最多16个字符啦'}, min_length = 8, max_length = 16)
    new_password1 = forms.CharField(label="新密码", widget=forms.PasswordInput, error_messages = {'required': u'新密码不能为空哦', 'min_length':u'至少8个字符啦', 'max_length':u'最多16个字符啦'}, min_length = 8, max_length = 16)
    new_password2 = forms.CharField(label="新密码确认", widget=forms.PasswordInput, error_messages = {'required': u'新密码不能为空哦', 'min_length':u'至少8个字符啦', 'max_length':u'最多16个字符啦'}, min_length = 8, max_length = 16)


class ResetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(label="新密码", widget=forms.PasswordInput, error_messages = {'required': u'新密码不能为空哦', 'min_length':u'至少8个字符啦', 'max_length':u'最多16个字符啦'}, min_length = 8, max_length = 16)
    new_password2 = forms.CharField(label="新密码确认", widget=forms.PasswordInput, error_messages = {'required': u'新密码不能为空哦', 'min_length':u'至少8个字符啦', 'max_length':u'最多16个字符啦'}, min_length = 8, max_length = 16)

TOPIC=(
    ('ux','用户体验'),
    ('bug','有bug!'),
    ('suggestion','建议'),
)

class ContactForm(forms.Form):
    topic = forms.ChoiceField(choices=TOPIC,label="主题")
    message = forms.CharField(widget=forms.Textarea(),label="内容",error_messages = {'required': u'内容为空？元芳，这不科学。'})
    sender = forms.EmailField(required=False,label="联系邮箱")
    def clean_message(self):
        message = self.cleaned_data.get('message','')
        if len(message) < 8:
            raise forms.ValidationError("元芳多说一点别那么小气啦!")
        return message

home/views.py
# Create your views here.
from django.shortcuts import redirect
from django.template.response import TemplateResponse

def home(request):
    if request.user.is_authenticated():
        return redirect('/file/')
    else:
        return TemplateResponse(request,"home/index.html")

def about(request):
    return TemplateResponse(request,"home/about.html")

def major_id(request):
    return TemplateResponse(request,"home/major_id.html")

def thanks(request):
    return TemplateResponse(request,'home/thanks.html')

wydy/templates/base.html
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} {% endblock %}
    </title>
    <link href="/static/css/bootstrap.min.css" type="text/css" rel="stylesheet">
    <link href="/static/css/bootstrap-responsive.min.css" type="text/css" rel="stylesheet">
    <script type="text/javascript" src="/static/js/jquery.min.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.min.js"></script>

    <style type="text/css">
            html{
                padding:10px 0px;
            }
            body {
                padding-top: 20px;
                padding-bottom: 40px;
            }
            body, input, button, textarea, .page-stat_number {
                font-family: "Helvetica Neue",Arial,Helvetica,sans-serif;
            }
            .extraheader{
                background-color: #F3F3F3;
                padding-bottom: 15px;
                padding-top: 25px;
            }
            .extratitle{
                font-size:25px;
            }
            .header1{
                font-size:30px;
                font-weight:bold;
                color:#0066ff;

            }
            .form-actions{
                background-color: #fff;
                border-style:none
            }

            .header1:hover{
                color:#0066ff;
                text-decoration:none;

            }
            .header2{
                font-size:30px;
                font-weight:bold;
                color:#00ccff;
            }
            .header2:hover{
                color:#00ccff;
                text-decoration:none;
            }
            div{margin:0;border:0;padding:0;}

            fieldset {
                padding: 20px 0 ;
            }

            .banner1{
                font-size:80px;
                font-weight:bold;
                color:#434343;
            }
            .banner2{
                font-size:80px;
                font-weight:bold;
                color:#00ccff;

            }
            .forgot{
                color:#00ccff;
                font-size:18px;

            }
            .forgot:hover{
                text-decoration:none;
                color:#00ccff;
            }
            .btn-primary:hover{
                text-decoration:none;
                color:white;
                border-style:none;
                background:#3cf;
            }

            footer[role="contentinfo"] {
                padding: 15px 0 0 0;
                font-size: 18px;
                border-top: 2px solid #ddd;
                text-align:center;
                font-weight:normal;
            }
            label{
                font-size:17px;

            }
            .fileinput-button {
                position: relative;
                overflow: hidden;
                float: left;
                margin-right: 4px;
            }
            .fileinput-button input {
                position: absolute;
                top: 0;
                right: 0;
                margin: 0;
                border: solid transparent;
                border-width: 0 0 100px 200px;
                opacity: 0;
                filter: alpha(opacity=0);
                -moz-transform: translate(-300px, 0) scale(4);
                direction: ltr;
                cursor: pointer;
            }
            /* Fix for IE 6: */
            *html .fileinput-button {
                line-height: 22px;
                margin: 1px -3px 0 0;
            }

            /* Fix for IE 7: */
            *+html .fileinput-button {
                margin: 1px 0 0 0;
            }

            .form-horizontal .control-label {
                text-align:left;
            }


            span{
                font-size:18px;
            }
            legend{
                font-size:23px;
                font-weight:bold;
                width:940px;
            }
            .container{
                min-height:84px;
            }
            a:hover{
                text-decoration:none;
            }
            .btn-primary{
                display: inline-block;
                text-align: center;
                padding: 16px 0px 18px 0px;
                font-size: 36px;
                line-height: 40px;
                min-width: 200px;
                -webkit-border-radius: 42px;
                -moz-border-radius: 42px;
                -ms-border-radius: 42px;
                -o-border-radius: 42px;
                border-radius: 42px;
                color: white;
                background: #3CF;
                font-weight: bold;
                text-decoration: none;
                border: 0 none currentColor;
                cursor: pointer;
                -webkit-user-select: none;
                -moz-user-select: none;
                user-select: none;
                -webkit-appearance: none;
            }
            html, body, #wrap {height: 100%;}
            body > #wrap {height: auto; min-height: 100%;}
            #main {padding-bottom: 100px;}  /* 必须使用和footer相同的高度 */
            #footer {
                position: relative;
                margin-top: -100px; /* footer高度的负值 */
                height: 100px;
                clear:both;
            }
            .clearfix:after {
                content: ".";
                display: block;
                height: 0;
                clear: both;
                visibility: hidden;}
            .clearfix {display: inline-block;}
            /* Hides from IE-mac \*/
            * html .clearfix { height: 1%;}
            .clearfix {display: block;}
            /* End hide from IE-mac */
        </style>
            <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
            <!--[if lt IE 9]>
             <script src="</SCRIPT'">http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
             <![endif]-->
        <!--
            <script type="text/javascript">
                var Sys = {};
                var ua = navigator.userAgent.toLowerCase();
                var s;
                (s = ua.match(/msie ([\d.]+)/)) ? Sys.ie = s[1] :
                (s = ua.match(/firefox\/([\d.]+)/)) ? Sys.firefox = s[1] :
                (s = ua.match(/chrome\/([\d.]+)/)) ? Sys.chrome = s[1] :
                (s = ua.match(/opera.([\d.]+)/)) ? Sys.opera = s[1] :
                (s = ua.match(/version\/([\d.]+).*safari/)) ? Sys.safari = s[1] : 0;
                function go(){
                    location.replace("http://www.google.com/chrome");
                }
                //redirect
                if (Sys.ie=='6.0'|Sys.ie=='7.0'|Sys.ie=='8.0') go();
            </script>-->

</head>
<body>
    <div class="container" id="wrap">
        <div class="container clearfix" id="main">
	    <div class="container">
            {%block logo%}
            <div class="span3 offset2">
            {%endblock%}
                <a href="/"><img src="/static/img/logo.png"></a>
            </div>
            {%block rightheader%}
            <div class="span3 offset3">
                <p   style="padding:22px 0 0 0"><a class="btn-primary" href="/about/">关于</a></p>
            </div>
            {%endblock%}
        </div>
        {%block extraheader%}

        <div class="container">
            <div class="extraheader">
                <div class="offset2">
                    <div class="extratitle">
                        {%block extraheadertitle%}
                        {%endblock%}
                    </div>
                </div>
            </div>
        </div>
        {%endblock%}
        <div class = "container">
            {% block content %}
            {% endblock %}
        </div>
        </div>
    </div>
    <div id="footer" class="container">
        <footer role="contentinfo" style="color:#AEAEAE">
            Beta · Powered by Django · Created in JLU
        </footer>
    </div>
</body>
</html>

wydy/templates/contact.html
{% extends "order.html"  %}
{% block title %}用户反馈{% endblock %}
{%block extraheadertitle%}元芳，你怎么看？{%endblock%}

{% block content %}
<div ></div>
<div class="span6 offset2">
    <form class = "form-horizontal" action="." method="post">
        {% csrf_token %}
        {{form.as_p}}
        <div class="form-actions">
            <input type="submit" class="btn-primary" value="提交">&nbsp;
        </div>
    </form>
</div>
{% endblock %}

wydy/templates/home.html
{% extends "base.html" %}

{% block title %}我要打印{% endblock %}
{%block logo%}<div class="span3 offset2">{%endblock%}
{%block extraheader%}{%endblock%}

{% block content %}
<div class="container">
        <div class="span7 offset3">
                <p class="banner1" style="line-height:150%;padding:20px 0 0 0;">打印社排长龙?</p>
                <p class="banner1" style="line-height:150%;padding:0 0 20px 0;">快来&nbsp;<span class="banner2">51dayin</span>
                </p>
        </div>
</div>
<div class="constainer">
            <div class="span3 offset2">
                <a href="/login/" class="btn-primary">登录</a>
            </div>
            <div class="span3 offset3">
                <a href="/join/" class="btn-primary">注册</a>
	    </div>
</div>
        <div ></div>
        <div ></div>
        <div ></div>
        <div ></div>
        <div ></div>
        <div ></div>
        <div ></div>
        <div ></div>
        <div ></div>
        <div ></div>
        <div ></div>

</div>
{% endblock %}

wydy/templates/hot.html
{%extends "base.html"%}
{%block title%}热门打印{%endblock%}

wydy/templates/join.html
{% extends "base.html"%}
{% block title %}注册╮(╯▽╰)╭{% endblock %}
{%block extraheadertitle%}
注册
{%endblock%}
{% block content %}
<div class="span8 offset2">
<form class="form-horizontal" method="post">
    {% csrf_token %}
    <fieldset>
    
         <div class="control-group">
            
            <!-- Text input--><br/><br/>
            <label class="control-label" for="id_cardnumber">卡号</label>
            <div class="controls">
                <input type="text" placeholder="" class="input-xlarge" id="id_cardnumber" name="cardNumber">&nbsp;
                    {{form.cardNumber.errors.0}}
                    <p class="help-block">在打印社购买的充值卡的卡号⊙▽⊙</p>
                    </div>
        </div>
        
        <div class="control-group">
            
            <!-- Text input-->
            <label class="control-label" for="id_cardpassword">卡密</label>
            <div class="controls">
                <input type="text" placeholder="" class="input-xlarge" id="id_cardpassword" name="cardPassword">&nbsp;
                    {{form.cardPassword.errors.0}}
                    <p class="help-block"></p>
                    </div>
        </div>
        
        <div class="control-group">
            
            <!-- Text input-->
            <label class="control-label" for="id_username">帐号</label>
            <div class="controls">
                <input type="text" placeholder="壮哉我大计院是53开头" class="input-xlarge" id="id_username" name="username">&nbsp;
                    {{form.username.errors.0}}
                    <p class="help-block"style="line-height:150%">要用教学号哦(说了多少遍了不是行政号! ←_←
                    <br/>
                    傻傻分不清楚的童鞋请看 <a href="/major_id/">这里</a>
                    </p>
                    </div>
        </div>
        
        <div class="control-group">
            
            <!-- Text input-->
            <label class="control-label" for="id_password">密码</label>
            <div class="controls">
                <input type="password" placeholder="嘛..很多东西都是越长越好的" class="input-xlarge" id="id_password" name="password">&nbsp;
                    {{form.password.errors.0}}
                    <p class="help-block">8~16个字符</p>
                    </div>
        </div>
        
        <div class="control-group">
            
            <!-- Text input-->
            <label class="control-label" for="id_confirmpassword">重复</label>
            <div class="controls">
                <input type="password" placeholder="" class="input-xlarge" id="id_confirmpassword" name="confirm_password">&nbsp;
                    {{form.confirm_password.errors.0}}
                    <p class="help-block"></p>
                    </div>
        </div>
        
        <div class="control-group">
            
            <!-- Text input-->
            <label class="control-label" for="id_email">邮箱</label>
            <div class="controls">
                <input type="text" placeholder="fiftycent@people.cn" class="input-xlarge" id="id_email" name="email">&nbsp;
                    {{form.email.errors.0}}
                    <p class="help-block">用于找回密码，请正确填写哦</p>
                    </div>
        </div>
        
        <div class="control-group">
            
            <!-- Text input-->
            <label class="control-label" for="id_phone">手机</label>
            <div class="controls">
                <input type="text" placeholder="here's my number, so call me maybe" class="input-xlarge" id="id_phone" name="phone">&nbsp;
                    {{form.phone.errors.0}}
                    <p class="help-block">特殊情况什么的，打印社要联系你的啦</p>
                    </div>
        </div>
        
        </fieldset>
     
        <div class="form-actions">
            <button type="submit" class="btn-primary">注册</button>
        </div>

        
    
</form>
</div>
{% endblock %}

wydy/templates/login.html
{%extends "base.html"%}
{%block title%}登录{%endblock%}
{%block extraheadertitle%}登录{%endblock%}
{%block content%}
<div class="offset2">
<form class="form" method="post">
    {%csrf_token%}
    <fieldset>
        
        <div class="control-group">
            {{form.non_field_errors}}<br/>
            <label class="control-label" for="id_username">帐号</label>
            <div class="controls">
                <input type="text" id="id_username" name="username" class="input-xlarge" placeholder="学号">
                    <span>{{form.username.errors.0}}</span>
                    </div>
        </div>
        
        <div class="control-group">
            
            <label for="id_password" class="control-label">密码</label>
            <div class="controls">
                <input type="password" class="input-xlarge" id="id_password" name="password">
                    <span class="clearfix">{{form.password.erros.0}}</span>
                    </div>
        </div>
        <div>
        <a href="/reset/" class="forgot">忘记密码</a><br/><br/><br/>
        </div>
        <div class="form-actions">
            <button class="btn-primary" type="submit">登录</button><span>
            <span style="padding:0 0 0 40px"><a class="btn-primary" href="/join/">注册</a><span>
        </div>
        
    </fieldset>
</form>
    <div ></div>
    <div ></div>

</div>
{%endblock%}

wydy/templates/order.html
{% extends "base.html" %}
{% block title%}预约打印{%endblock%}

{%block rightheader%}
<div class="span5 offset1">
	<ul class="nav nav-pills" style="font-size:18px">
        <li class="{%if active == 'file'%}active{%endif%}"><a href='/file/'>预约打印</a></li>
        <li class="{%if active == 'tasklist'%}active{%endif%}"><a href='/user/tasklist/'>任务列表</a></li>
        <li class="{%if active == 'settings'%}active{%endif%}"><a href='/settings/profile/'>账户管理</a></li>
        <li class="{%if active == 'contact'%}active{%endif%}"><a href='/contact/'>吐槽</a></li>
        <li><a href='/logout/'>退出</a></li>
	</ul>
</div>
{%endblock%}

{%block extraheadertitle%}
预约打印，仅需4步
{%endblock%}

{%block content%}
<!--选择打印社-->
<div class="offset2">
    
    <form action="." class="form-horizontal" method="POST" style="padding:20px 0 0 0;">{%csrf_token%}
        
        <fieldset>
            <div id="legend" class="">
                <legend class="">选择打印社
                    <span class="pull-right" style="color:#DFDFDF;font-size:20px">
                        step 1 of 4
                    </span>
                </legend>
            </div>
            
            <div class="control-group">
                <label class="control-label"></label>
                <div class="controls">
                    <select name="printhouse" class="input-xlarge">
                        <option value="经C">经C泰和书屋旁打印社</option>
                    </select>{{form.printhouse.errors.0}}
                </div>
            </div>
            
        </fieldset>
        <fieldset>
            <div id="legend" class="">
                <legend class="">选择上门提取文件的时间
                    <span class="pull-right" style="color:#DFDFDF;font-size:20px">
                        step 2 of 4
                    </span>
                </legend>
            </div>
            <span>我会在&nbsp;</span>
            <select  name="day" class="input-small">
                <option value="0">当日</option>
                <option value="1">次日</option>
            </select>{{form.day.errors.0}}
            <span>&nbsp;的&nbsp;</span>
            <select  name="hour" class="input-small">
                <option value="07">7</option>
                <option value="08">8</option>
                <option value="09">9</option>
                <option value="10">10</option>
                <option value="11">11</option>
                <option value="12">12</option>
                <option value="13">13</option>
                <option value="14">14</option>
                <option value="15">15</option>
                <option value="16">16</option>
                <option value="17">17</option>
                <option value="18">18</option>
                <option value="19">19</option>
                <option value="20">20</option>
                <option value="21">21</option>
                <option value="22">22</option>
            </select>{{form.hour.errors.0}}
            <span>&nbsp;时&nbsp;</span>
            <label class="control-label"></label>
            <select  name="minute" class="input-small">
                <option value="00">00</option>
                <option value="05">05</option>
                <option value="10">10</option>
                <option value="15">15</option>
                <option value="20">20</option>
                <option value="25">25</option>
                <option value="30">30</option>
                <option value="35">35</option>
                <option value="40">40</option>
                <option value="45">45</option>
                <option value="50">50</option>
                <option value="55">55</option>
            </select>{{form.minute.errors.0}}
            <span>&nbsp;分&nbsp;后到打印社提取</span>
        </fieldset>
        <div class="offset1" style="padding:20px 0px 30px 40px;">
            <span>打印社营业时间 7:00~23:00</span>
        </div>
        <div class="form-actions">
            <button type="submit" class="btn-primary">下一步</button>
        </div>
    </form>
</div>

{% endblock %}

wydy/templates/result.html
{%extends "base.html"%}
{%block title%}上传结果{%endblock%}

{%block content%}

<script>
    document.body.innerText=document.body.textContent=decodeURIComponent(window.location.search.slice(1));
    alert(document.body.innerText);
    </script>
{%endblock%}

wydy/templates/success.html
{% extends "order.html" %}
{%block extraheadertitle%}
预约完成
{%endblock%}

{%block content%}
<div class="offset2">
    <p style="font-size:20px;line-height:200%;padding:20px 0">恭喜你，预约已完成！你的预约编号为 <span style="color:#33ccff;font-size:25px">{{resv_number}}</span><br/>请在预约好的时间，凭借此编号去相应打印社取文件。现场付款。<br/>记得及时取文件哦~你的文件会在服务器上保留48小时。</p>
    <div style="padding:30px 0">
    <a class="btn btn-primary" href="/file/">返回</a>
    </div>
</div>
{%endblock%}

wydy/templates/thanks.html
{%extends "user.html"%}
{%block title%}Thanks{%endblock%}
{%block extraheadertitle%}Thanks{%endblock%}
{%block content%}
<div class="span12"></div>
    <div class="offset2" style="font-size:20px;">
<meta http-equiv="refresh" content="1;url=/user/">
    谢谢你的建议哦~
<div class="span12"></div>
    <div class="span12"></div>

    <div class="span12"></div>

    <div class="span12"></div>

</div>
{%endblock%}